/* jshint globalstrict: true */
'use strict';

module.exports = {
    locales: ['en-us', 'es'],
    messages: {
        'en-us' : {
            'home': {
                'title': "Frontend Template",
                'content': "...sorry the name isn't better."
            },
            "404": {
                "site-not-found": "Sorry, that page was not found."
            },
            "fmt": {
                "Date": "Date",
                "Number": "Number",
                "Time": "Time",
                "Relative Time": "Relative Time",
                "Currency": "Currency",
                "Formatted Message": "Formatted Message",
                "messages": "{name}, you have {numMessages, plural,\n  =0 {no messages}\n  =1 {one message}\n  other {# messages}\n}.\n"
            },
            "sg": {
                "title": "Style Guide",
                "section": {
                    "Kitchen Sink": "Kitchen Sink",
                    "Typography": "Typography",
                    "Buttons": "Buttons",
                    "Icons": "Icons",
                    "Form Elements": "Form Elements"
                },
                "buttons": {
                    "a": "Default Button <a> Element",
                    "button": "Default Button <button> Element",
                    "sizes": "Button Sizes",
                    "tiny": "Tiny Button",
                    "small": "Small Button",
                    "medium": "Medium Button",
                    "large": "Large Button",
                    "split": "Split Button",
                    "split-right": "Split Buttons (Right)",
                    "split-left": "Split Buttons (Left)",
                    "themes": "Button Themes",
                    "primary-color" : "Primary Color Button",
                    "secondary-color" : "Secondary Color Button",
                    "tertiary-color" : "Tertiary Color Button",
                    "inherit" : "Inherit Button",
                    "status" : "Status Buttons",
                    "warning" : "Warning Button",
                    "warning-alt" : "Warning Alternate Button",
                    "display-types" : "Button Display Types",
                    "block-level" : "Block Level Button",
                    "disabled" : "Disabled Button"
                },
                "form-elements": {
                    "validation-warning" : "Warning message 1",
                    "validation-error" : "Error message",
                    "validation-success" : "Success message",
                    "option-1" : "Option 1",
                    "option-2" : "Option 2",
                    "option-3" : "Option 3",
                    "option-4" : "Option 4",
                    "radio-option-1" : "Radio option 1",
                    "radio-option-2" : "Radio option 2",
                    "radio-option-3" : "Radio option 3",
                    "checkbox-option-1" : "Checkbox option 1",
                    "checkbox-option-2" : "Checkbox option 2",
                    "checkbox-option-3" : "Checkbox option 3",
                    "radio-option-1-2" : "Radio option 1-2",
                    "radio-option-2-2" : "Radio option 2-2",
                    "radio-option-3-2" : "Radio option 3-2",
                    "checkbox-option-1-2" : "Checkbox option 1-2",
                    "checkbox-option-2-2" : "Checkbox option 2-2",
                    "checkbox-option-3-2" : "Checkbox option 3-2",
                    "input-types" : "Input types",
                    "basic-label" : "Basic text input:",
                    "basic-placeholder" : "Text input",
                    "email-label" : "Email text input:",
                    "email-placeholder" : "Ex: anybody@anywhere.com",
                    "pwd-label" : "Password text input:",
                    "pwd-placeholder" : "Enter your password",
                    "search-label" : "Search text input:",
                    "search-placeholder" : "Search terms",
                    "url-label" : "URL text input:",
                    "url-placeholder" : "Ex: http://anywhere.org",
                    "phone-label" : "Phone text input:",
                    "phone-placeholder" : "Ex: (555) 555-5555",
                    "number-label" : "Number text input:",
                    "number-placeholder" : "Enter your lucky number",
                    "textarea-label" : "Textarea:",
                    "textarea-placeholder" : "Tell us a bit about yourself...",
                    "date-label" : "Date text input:",
                    "date-placeholder" : "MM/DD/YYYY",
                    "datetime-label" : "Datetime text input:",
                    "datetime-placeholder" : "MM/DD/YYYY",
                    "datetime-local-label" : "Datetime-local text input:",
                    "datetime-local-placeholder" : "MM/DD/YYYY EST",
                    "month-label" : "Month text input:",
                    "month-placeholder" : "Month you were born",
                    "week-label" : "Week text input:",
                    "week-placeholder" : "Week",
                    "day-label" : "Day text input:",
                    "day-placeholder" : "Tuesday",
                    "select-label" : "Select input:",
                    "radio-label" : "Single radio input",
                    "radio-group-label" : "Radio Group",
                    "checkbox-label" : "Single checkbox-single input",
                    "checkbox-group-label" : "Checkbox Group",
                    "radio-group-inline-label" : "Inline Radio Group",
                    "checkbox-group-inline-label" : "Checkbox Group",
                    "validation" : "Validation",
                    "input-validation-warning-label" : "Validation warning:",
                    "input-validation-warning-placeholder" : "Email input",
                    "input-validation-error-label" : "Validation error:",
                    "input-validation-error-placeholder" : "Enter a number",
                    "input-validation-success-label" : "Validation success:",
                    "input-validation-success-placeholder" : "Email address",
                    "input-validation-warning-pos-label" : "Validation warning (positioned):",
                    "input-validation-warning-pos-placeholder" : "Email input",
                    "input-validation-error-pos-label" : "Validation error (positioned):",
                    "input-validation-error-pos-placeholder" : "Email input",
                    "input-validation-success-pos-label" : "Validation success (positioned):",
                    "input-validation-success-pos-placeholder" : "Email input"
                },
                "icons" : {
                    "icon" : "Icon: ",
                    "navicon" : "navicon",
                    "caret" : "caret",
                    "icon-sizes" : "Icon sizes",
                    "xs" : "Extra Small",
                    "s" : "Small",
                    "m" : "Medium",
                    "l" : "Large",
                    "xl" : "Extra Large",
                    "icon-rotation" : "Icon rotation",
                    "0deg" : "0deg Rotation",
                    "45deg" : "45deg Rotation",
                    "90deg" : "90deg Rotation",
                    "180deg" : "180deg Rotation",
                    "270deg" : "270deg Rotation",
                    "icon-colors" : "Icon colors",
                    "black" : "Black fill",
                    "white" : "White fill",
                    "primary" : "Primary fill",
                    "secondary" : "Secondary fill",
                    "tertiary" : "Tertiary fill"
                },
                "typography" : {
                    "headers" : "Headers",
                    "h1" : "Heading H1",
                    "h2" : "Heading H2",
                    "h3" : "Heading H3",
                    "h4" : "Heading H4",
                    "h5" : "Heading H5",
                    "h6" : "Heading H6",
                    "grouping" : "Grouping elements",
                    "p" : "Paragraph",
                    "blockquote" : "Blockquote",
                    "inline-elements" : "Inline elements",
                    "a" : "Anchor",
                    "strong" : "Strong Tag",
                    "b" : "B Tag",
                    "em" : "Em tag",
                    "i" : "I tag",
                    "sub" : "Sub tag",
                    "sup" : "Sup tag",
                    "dfn" : "Dfn tag"
                }
            }
        },
        'es' : {
            'home': {
                'title': "Frontend Template - Spanish",
                'content': "...sorry the name isn't better."
            },
            "404": {
                "site-not-found": "Sorry, that page was not found."
            },
            "sg": {
                "title": "Style Guide",
                "section": {
                    "Kitchen Sink": "Kitchen Sink",
                    "Typography": "Typography",
                    "Buttons": "Buttons",
                    "Icons": "Icons",
                    "Form Elements": "Form Elements"
                },
                "buttons": {
                    "a": "Default Button <a> Element",
                    "button": "Default Button <button> Element",
                    "sizes": "Button Sizes",
                    "tiny": "Tiny Button",
                    "small": "Small Button",
                    "medium": "Medium Button",
                    "large": "Large Button",
                    "split": "Split Button",
                    "split-right": "Split Buttons (Right)",
                    "split-left": "Split Buttons (Left)",
                    "themes": "Button Themes",
                    "primary-color" : "Primary Color Button",
                    "secondary-color" : "Secondary Color Button",
                    "tertiary-color" : "Tertiary Color Button",
                    "inherit" : "Inherit Button",
                    "status" : "Status Buttons",
                    "warning" : "Warning Button",
                    "warning-alt" : "Warning Alternate Button",
                    "display-types" : "Button Display Types",
                    "block-level" : "Block Level Button",
                    "disabled" : "Disabled Button"
                },
                "form-elements": {
                    "validation-warning" : "Warning message 1",
                    "validation-error" : "Error message",
                    "validation-success" : "Success message",
                    "option-1" : "Option 1",
                    "option-2" : "Option 2",
                    "option-3" : "Option 3",
                    "option-4" : "Option 4",
                    "radio-option-1" : "Radio option 1",
                    "radio-option-2" : "Radio option 2",
                    "radio-option-3" : "Radio option 3",
                    "checkbox-option-1" : "Checkbox option 1",
                    "checkbox-option-2" : "Checkbox option 2",
                    "checkbox-option-3" : "Checkbox option 3",
                    "radio-option-1-2" : "Radio option 1-2",
                    "radio-option-2-2" : "Radio option 2-2",
                    "radio-option-3-2" : "Radio option 3-2",
                    "checkbox-option-1-2" : "Checkbox option 1-2",
                    "checkbox-option-2-2" : "Checkbox option 2-2",
                    "checkbox-option-3-2" : "Checkbox option 3-2",
                    "input-types" : "Input types",
                    "basic-label" : "Basic text input:",
                    "basic-placeholder" : "Text input",
                    "email-label" : "Email text input:",
                    "email-placeholder" : "Ex: anybody@anywhere.com",
                    "pwd-label" : "Password text input:",
                    "pwd-placeholder" : "Enter your password",
                    "search-label" : "Search text input:",
                    "search-placeholder" : "Search terms",
                    "url-label" : "URL text input:",
                    "url-placeholder" : "Ex: http://anywhere.org",
                    "phone-label" : "Phone text input:",
                    "phone-placeholder" : "Ex: (555) 555-5555",
                    "number-label" : "Number text input:",
                    "number-placeholder" : "Enter your lucky number",
                    "textarea-label" : "Textarea:",
                    "textarea-placeholder" : "Tell us a bit about yourself...",
                    "date-label" : "Date text input:",
                    "date-placeholder" : "MM/DD/YYYY",
                    "datetime-label" : "Datetime text input:",
                    "datetime-placeholder" : "MM/DD/YYYY",
                    "datetime-local-label" : "Datetime-local text input:",
                    "datetime-local-placeholder" : "MM/DD/YYYY EST",
                    "month-label" : "Month text input:",
                    "month-placeholder" : "Month you were born",
                    "week-label" : "Week text input:",
                    "week-placeholder" : "Week",
                    "day-label" : "Day text input:",
                    "day-placeholder" : "Tuesday",
                    "select-label" : "Select input:",
                    "radio-label" : "Single radio input",
                    "radio-group-label" : "Radio Group",
                    "checkbox-label" : "Single checkbox-single input",
                    "checkbox-group-label" : "Checkbox Group",
                    "radio-group-inline-label" : "Inline Radio Group",
                    "checkbox-group-inline-label" : "Checkbox Group",
                    "validation" : "Validation",
                    "input-validation-warning-label" : "Validation warning:",
                    "input-validation-warning-placeholder" : "Email input",
                    "input-validation-error-label" : "Validation error:",
                    "input-validation-error-placeholder" : "Enter a number",
                    "input-validation-success-label" : "Validation success:",
                    "input-validation-success-placeholder" : "Email address",
                    "input-validation-warning-pos-label" : "Validation warning (positioned):",
                    "input-validation-warning-pos-placeholder" : "Email input",
                    "input-validation-error-pos-label" : "Validation error (positioned):",
                    "input-validation-error-pos-placeholder" : "Email input",
                    "input-validation-success-pos-label" : "Validation success (positioned):",
                    "input-validation-success-pos-placeholder" : "Email input"
                },
                "icons" : {
                    "icon" : "Icon: ",
                    "navicon" : "navicon",
                    "caret" : "caret",
                    "icon-sizes" : "Icon sizes",
                    "xs" : "Extra Small",
                    "s" : "Small",
                    "m" : "Medium",
                    "l" : "Large",
                    "xl" : "Extra Large",
                    "icon-rotation" : "Icon rotation",
                    "0deg" : "0deg Rotation",
                    "45deg" : "45deg Rotation",
                    "90deg" : "90deg Rotation",
                    "180deg" : "180deg Rotation",
                    "270deg" : "270deg Rotation",
                    "icon-colors" : "Icon colors",
                    "black" : "Black fill",
                    "white" : "White fill",
                    "primary" : "Primary fill",
                    "secondary" : "Secondary fill",
                    "tertiary" : "Tertiary fill"
                },
                "typography" : {
                    "headers" : "Headers",
                    "h1" : "Heading H1",
                    "h2" : "Heading H2",
                    "h3" : "Heading H3",
                    "h4" : "Heading H4",
                    "h5" : "Heading H5",
                    "h6" : "Heading H6",
                    "grouping" : "Grouping elements",
                    "p" : "Paragraph",
                    "blockquote" : "Blockquote",
                    "inline-elements" : "Inline elements",
                    "a" : "Anchor",
                    "strong" : "Strong Tag",
                    "b" : "B Tag",
                    "em" : "Em tag",
                    "i" : "I tag",
                    "sub" : "Sub tag",
                    "sup" : "Sup tag",
                    "dfn" : "Dfn tag"
                }
            }
        }
    }
};
